### ISSUE TITLE
Usage question (or improvement request)

### ISSUE THREAD

**Issue by theo-staizen** [byu-oit/github-action-disallow-concurrent-runs#14]
Hi,

I was wondering if this action can be used/adapted to achieve a flow similar to other CI tools (jenkins, bamboo), which would simply queue a single job for all changes that came in while another job was already in progress. E.g:

1. PR is open => Job A starts
2. A new commit is pushed to branch => Job B is queued
3. Two more commit are pushed to the branch => Job B is updated (or is cancelled and Job C is queued)
4. Job A is finished => Job B (or C) starts running **ONE TIME** for all 3 new commits

Thanks

**Comment by joshgubler** [comment]
GitHub Actions now supports this natively: https://docs.github.com/en/actions/using-jobs/using-concurrency
