### ISSUE TITLE
Does this work on pull_requests?

### ISSUE THREAD

**Issue by rlorenzo** [byu-oit/github-action-disallow-concurrent-runs#8]
Can you see if I am doing something wrong here? When I have this action nothing runs even if there are no concurrent tasks running. This is the commit I added:

https://github.com/ucla/aws-refarch-moodle/commit/836469140fa0930e50a474fa116b6908487fee45

But I get a "Workflow runs completed with no jobs" when I push changes to the branch.

![Screen Shot 2020-11-30 at 12 02 24 PM](https://user-images.githubusercontent.com/349765/100658500-044d6980-3304-11eb-9968-02b12736fa5b.png)

The only difference I have from your example is that I have the action set to run for pull_requests rather than on push. So does this action not work for pull_requests?

**Comment by rlorenzo** [comment]
I think our error was because there were some merge conflicts so tasks didn't run. We resolved that, but are getting another error now:

Error: An error occurred: Cannot read property 'slice' of undefined

![Screen Shot 2020-11-30 at 2 41 46 PM](https://user-images.githubusercontent.com/349765/100674567-34a00280-331a-11eb-8e2d-e3fbebcc5a51.png)

Our changes: https://github.com/ucla/aws-refarch-moodle/pull/3/files

**Comment by GaryGSC** [comment]
>Does this work on pull_requests?

It doesn't currently, but I'm thinking of adding support in an upcoming release that I think we'll call `v2`. Keep an eye on #9.
